# Generated by Django 4.1.1 on 2022-10-02 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=150, verbose_name="Full Name"),
                ),
                ("url_name", models.CharField(max_length=100, verbose_name="URL Name")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.node",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Nodes",
                "ordering": ("url_name",),
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[],
            options={
                "verbose_name_plural": "Categories",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("products.node",),
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[],
            options={
                "verbose_name_plural": "Sub Categories",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("products.node",),
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Product Name")),
                (
                    "code",
                    models.CharField(
                        default="", max_length=50, verbose_name="Product Code"
                    ),
                ),
                ("price", models.IntegerField(default=0)),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Product Description"),
                ),
                ("image", models.ImageField(upload_to="products_images")),
                (
                    "review",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Product Review",
                    ),
                ),
                ("isActive", models.BooleanField(blank=True)),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.subcategory",
                    ),
                ),
            ],
        ),
    ]
