# Generated by Django 4.1.1 on 2022-10-07 11:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(max_length=150, verbose_name="Category Name"),
                ),
                ("slug", models.SlugField(blank=True)),
                (
                    "category_image",
                    models.ImageField(
                        blank=True,
                        upload_to="category_images",
                        verbose_name="Category Image",
                    ),
                ),
                (
                    "category_icon",
                    models.ImageField(
                        blank=True,
                        upload_to="category_icons",
                        verbose_name="Category Icon",
                    ),
                ),
            ],
            options={
                "ordering": ("category_name",),
            },
        ),
        migrations.CreateModel(
            name="SubCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sub_category_name",
                    models.CharField(max_length=150, verbose_name="SubCategory Name"),
                ),
                ("slug", models.SlugField(blank=True)),
                (
                    "sub_category_image",
                    models.ImageField(
                        blank=True,
                        upload_to="sub_category_images",
                        verbose_name="Sub Category Image",
                    ),
                ),
                (
                    "sub_category_icon",
                    models.ImageField(
                        blank=True,
                        upload_to="sub_category_icons",
                        verbose_name="Sub Category Icon",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcategories",
                        to="products.category",
                    ),
                ),
            ],
            options={
                "ordering": ("sub_category_name",),
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Product Name")),
                ("slug", models.SlugField(blank=True)),
                (
                    "code",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Product Code (optional)",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=3, max_digits=8)),
                (
                    "description",
                    models.TextField(
                        blank=True, verbose_name="Product Description (optional)"
                    ),
                ),
                (
                    "properties",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            blank=True, default="", max_length=50
                        ),
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="products_images", verbose_name="Product Image"
                    ),
                ),
                (
                    "review",
                    models.URLField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Product Review (optional)",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        upload_to="products_images",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "isActive",
                    models.BooleanField(
                        blank=True, verbose_name="Is Product Present (optional)"
                    ),
                ),
                ("data_added", models.DateTimeField(auto_now_add=True)),
                (
                    "sub_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="products.subcategory",
                    ),
                ),
            ],
            options={
                "ordering": ("-data_added",),
            },
        ),
    ]
