# Generated by Django 4.1.1 on 2022-10-07 11:57

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_alter_product_properties"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="properties",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, default="", max_length=100),
                default=list,
                size=None,
            ),
        ),
    ]
