# Generated by Django 4.1.1 on 2022-10-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_image_alter_product_properties"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image2",
            field=models.ImageField(
                blank=True,
                upload_to="products_images",
                verbose_name="Third Product Image (optional)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="title_image",
            field=models.ImageField(
                blank=True,
                upload_to="products_images",
                verbose_name="Product Title Image",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=models.ImageField(
                blank=True,
                upload_to="products_images",
                verbose_name="Second Product Image (optional)",
            ),
        ),
    ]
