# Generated by Django 4.1.1 on 2022-10-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_product_image2_product_title_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="title_image",
            field=models.ImageField(
                upload_to="products_images", verbose_name="Product Title Image"
            ),
        ),
    ]
