# Generated by Django 4.1.1 on 2022-10-12 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_product_title_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="consumption",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                verbose_name="Product Consumption (Потребление)",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="dimensions",
            field=models.CharField(
                blank=True,
                default="",
                max_length=50,
                verbose_name="Product Dimensions (Габариты)",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.subcategory"
            ),
        ),
    ]
