# Generated by Django 4.1.1 on 2023-02-01 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlideImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideName', models.CharField(max_length=255, verbose_name='Slide Name')),
                ('slideSlug', models.SlugField(blank=True)),
                ('slideImage', models.ImageField(upload_to='slide_images', verbose_name='Slide Image')),
            ],
        ),
    ]
